# bundle exec jekyll serve --livereload -w -o
# jekyll build

# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Max Chumley
# Description of the Site
description: Mechanical Engineering PhD. Student
# URL of Image of the Site
site-image: /assets/images/basin_new.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/basin_new.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: chumleym@msu.edu

github_username:  maxchumley
linkedin_username: max-chumley
orcid: 0000-0002-5335-5409
gscholar: 9hlMDN0AAAAJ&hl



# # Google Analytics
# google-analytics: 

# Disqus
disqus-shortname: ""

# Name of the Author
author-name: Max Chumley
# URL for the Image of the Author
author-image: /assets/images/max_portrait.png
# 60 Words About the Author
author-about: I am a second year mechanical engineering Ph.D. student at Michigan State University. My research focuses on nonlinear dynamical systems and timeseries analysis using topological data analysis.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/maxchumley

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
